import { motion } from 'framer-motion';
import SEO, { breadcrumbJsonLd } from '../components/common/SEO';

function LegalPage({ title, description, path, lastUpdated, sections }) {
  return (
    <div className="pt-32 pb-20 max-w-3xl mx-auto px-6">
      <SEO
        title={title}
        description={description}
        url={path}
        jsonLd={breadcrumbJsonLd([
          { name: 'Home', url: '/' },
          { name: title, url: path },
        ])}
      />
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-4xl font-bold mb-2">{title}</h1>
        <p className="text-muted text-sm mb-10">Last updated: {lastUpdated}</p>
        <div className="space-y-8">
          {sections.map((section) => (
            <div key={section.heading}>
              <h2 className="text-xl font-black mb-3 text-zaa-orange">{section.heading}</h2>
              <p className="text-secondary leading-relaxed">{section.content}</p>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
}

export function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      description="Zeno Africa Adventures Privacy Policy — learn how we collect, use, protect, and manage your personal data when you use our safari booking and travel services."
      path="/privacy"
      lastUpdated="July 2025"
      sections={[
        { heading: '1. Introduction', content: 'Zeno Africa Adventures ("we", "our", "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website, use our booking services, or interact with us in any capacity. By using our services, you consent to the practices described in this policy.' },
        { heading: '2. Information We Collect', content: 'We collect information that you provide directly to us, including: (a) Personal identifiers such as your full name, email address, phone number, and postal address; (b) Travel documents including nationality, passport numbers, date of birth, and visa details required for booking and visa processing; (c) Payment information such as credit/debit card numbers, billing addresses, and transaction history processed securely through Stripe; (d) Account credentials including your username and encrypted password; (e) Communication records including emails, chat messages, and support tickets you send to us; (f) Dietary requirements, medical conditions, accessibility needs, and other special requests you share for trip customisation.' },
        { heading: '3. How We Collect Information', content: 'We collect information through: (a) Direct interactions when you create an account, make a booking, apply for visa assistance, fill out a contact form, or communicate with our team; (b) Automated technologies including cookies, server logs, and analytics tools that collect usage data such as your IP address, browser type, operating system, pages visited, time spent on pages, and referral URLs; (c) Third-party sources such as payment processors (Stripe), analytics providers (Google Analytics), and social media platforms when you log in using a third-party account.' },
        { heading: '4. How We Use Your Information', content: 'We use your information to: (a) Process and confirm bookings, send itineraries, and manage your travel arrangements; (b) Facilitate visa applications by preparing documentation and communicating with relevant embassies and consulates; (c) Process payments securely and send receipts and invoices; (d) Send booking confirmations, pre-trip information, and post-trip follow-ups; (e) Respond to your enquiries, complaints, and support requests; (f) Send marketing communications about new packages, promotions, and travel tips — you may opt out at any time by clicking "unsubscribe" or contacting us directly; (g) Improve our website, services, and customer experience through analytics and feedback; (h) Comply with legal obligations, resolve disputes, and enforce our terms of service.' },
        { heading: '5. Legal Basis for Processing', content: 'We process your personal data under the following legal bases: (a) Contractual necessity — processing required to fulfil your booking agreement; (b) Legitimate interests — improving our services, preventing fraud, and ensuring platform security; (c) Consent — for marketing communications and optional cookies; (d) Legal obligation — compliance with tax laws, travel regulations, and government reporting requirements.' },
        { heading: '6. Data Sharing and Disclosure', content: 'We share your information only as necessary to deliver our services: (a) Service providers including hotels, safari lodges, airlines, ground transport operators, and tour guides who fulfil your travel arrangements; (b) Visa processing authorities and embassies for visa application processing; (c) Payment processors (Stripe) for secure transaction handling; (d) Cloud infrastructure providers (MongoDB Atlas, Cloudinary) for secure data and file storage; (e) Analytics providers (Google Analytics) to understand website usage patterns. We do not sell, rent, or trade your personal information to third parties for their marketing purposes.' },
        { heading: '7. Data Security', content: 'We implement robust security measures to protect your data: (a) 256-bit SSL/TLS encryption for all data transmitted between your browser and our servers; (b) Bcrypt password hashing — we never store or have access to your plaintext password; (c) Secure payment processing through Stripe, a PCI-DSS Level 1 certified payment processor — we do not store credit card details on our servers; (d) Role-based access controls limiting employee access to personal data; (e) Regular security audits and dependency updates; (f) Rate limiting and DDoS protection on all API endpoints.' },
        { heading: '8. Data Retention', content: 'We retain your personal data for as long as necessary to fulfil the purposes outlined in this policy: (a) Account data is retained for the lifetime of your account and for 30 days after deletion; (b) Booking records are retained for 7 years to comply with tax and financial regulations; (c) Marketing preferences are retained until you withdraw consent; (d) Server logs are automatically purged after 90 days; (e) Cookie data expires according to the durations specified in our cookie policy.' },
        { heading: '9. Your Rights', content: 'You have the following rights regarding your personal data: (a) Right of access — request a copy of all personal data we hold about you; (b) Right to rectification — request correction of inaccurate or incomplete data; (c) Right to erasure ("right to be forgotten") — request deletion of your personal data, subject to legal retention obligations; (d) Right to restrict processing — request that we limit how we use your data; (e) Right to data portability — receive your data in a structured, machine-readable format; (f) Right to object — opt out of processing based on legitimate interests, including direct marketing. To exercise any of these rights, contact us at zenoafricaadventures@gmail.com. We will respond within 30 days.' },
        { heading: '10. Cookies and Tracking Technologies', content: 'We use the following types of cookies: (a) Essential cookies — required for login sessions, shopping cart functionality, and security features; (b) Preference cookies — remember your settings such as language and currency preferences; (c) Analytics cookies — help us understand how visitors interact with our website (Google Analytics); (d) Marketing cookies — used to deliver relevant advertisements and track campaign performance. You can manage cookie preferences through your browser settings. Disabling essential cookies may impair website functionality.' },
        { heading: '11. Children\'s Privacy', content: 'Our services are not directed to individuals under the age of 18. We do not knowingly collect personal information from children. If we become aware that we have collected data from a child under 18, we will take steps to delete that information promptly. If you are a parent or guardian and believe your child has provided us with personal data, please contact us immediately.' },
        { heading: '12. International Data Transfers', content: 'Your data may be processed in countries outside your country of residence, including Tanzania and the United States, where our servers and service providers are located. These countries may have different data protection laws. We ensure appropriate safeguards are in place, including standard contractual clauses and data processing agreements with all third-party processors.' },
        { heading: '13. Changes to This Policy', content: 'We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated "Last Updated" date. Material changes will be communicated via email to registered users. We encourage you to review this policy periodically.' },
        { heading: '14. Contact Us', content: 'For any questions, concerns, or requests related to this Privacy Policy or your personal data, please contact: Zeno Africa Adventures — Email: zenoafricaadventures@gmail.com — Phone: +255 674 448 795 — Address: Tanzania, East Africa.' },
      ]}
    />
  );
}

export function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      description="Zeno Africa Adventures Terms of Service — booking conditions, cancellation policy, payment terms, liability, and user obligations for our safari and travel services."
      path="/terms"
      lastUpdated="July 2025"
      sections={[
        { heading: '1. Acceptance of Terms', content: 'By accessing the Zeno Africa Adventures website (zenoafricaadventures.com), creating an account, making a booking, or using any of our services, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, you must not use our website or services. These terms constitute a legally binding agreement between you and Zeno Africa Adventures.' },
        { heading: '2. Definitions', content: '"Company", "we", "our", "us" refers to Zeno Africa Adventures. "Customer", "you", "traveller" refers to any individual who uses our services or makes a booking. "Booking" refers to a confirmed reservation for a travel package, safari, tour, or related service. "Package" refers to a curated travel experience offered on our platform including accommodation, transport, guides, and activities. "Services" refers to all services provided through our website including booking, visa assistance, travel consultation, and customer support.' },
        { heading: '3. Account Registration', content: 'To make a booking, you must create an account. You agree to: (a) Provide accurate, current, and complete information during registration; (b) Maintain the security of your password and accept all risks of unauthorised access; (c) Notify us immediately at zenoafricaadventures@gmail.com if you suspect unauthorised use of your account; (d) Accept responsibility for all activities that occur under your account. We reserve the right to suspend or terminate accounts that provide false information or violate these terms.' },
        { heading: '4. Booking and Payment', content: '4.1 Booking Process: Bookings are confirmed only after we send you a written confirmation email. A booking does not constitute a contract until confirmed. 4.2 Deposit: A deposit of 30-40% of the total package price is required to secure your booking. The deposit amount will be specified at the time of booking. 4.3 Balance Payment: The remaining balance is due no later than 30 days before your scheduled travel date unless otherwise specified. 4.4 Payment Methods: We accept major credit/debit cards processed securely through Stripe. Bank transfers are available for high-value bookings. 4.5 Currency: All prices are displayed in USD unless otherwise stated. Exchange rate fluctuations are the customer\'s responsibility. 4.6 Price Changes: We reserve the right to adjust prices due to factors beyond our control, including currency fluctuations, government taxes, or fuel surcharges. Any price increase exceeding 10% entitles you to cancel with a full refund of all amounts paid.' },
        { heading: '5. Cancellation Policy', content: '5.1 Customer-Initiated Cancellations: Cancellation refunds are calculated based on the number of days before the travel date: (a) More than 60 days before travel: 90% refund of all amounts paid; (b) 31-60 days before travel: 50% refund; (c) 15-30 days before travel: 25% refund; (d) Less than 14 days before travel: No refund. 5.2 How to Cancel: Submit cancellation requests through your dashboard under "My Bookings" or email us at zenoafricaadventures@gmail.com with your booking reference number. 5.3 Non-Refundable Items: Gorilla trekking permits, chimpanzee permits, and certain third-party reservations may be non-refundable regardless of cancellation timing. This will be clearly stated at the time of booking. 5.4 Company-Initiated Cancellations: We may cancel or modify bookings due to natural disasters, political instability, public health emergencies, or insufficient bookings. In such cases, you will receive a full refund or the option to reschedule at no additional cost.' },
        { heading: '6. Changes and Modifications', content: '6.1 Customer-Requested Changes: We will make reasonable efforts to accommodate changes to dates, room types, or activities after booking. Changes are subject to availability and may incur additional costs. Request changes through your dashboard or by contacting our team. 6.2 Company-Requested Changes: We reserve the right to make reasonable modifications to itineraries due to weather, road conditions, wildlife movements, safety concerns, or government regulations. Any change will maintain the overall quality and value of your experience. If a significant change materially alters your trip, you may choose an alternative of comparable value or cancel for a full refund.' },
        { heading: '7. Travel Documents and Requirements', content: '7.1 It is your responsibility to ensure you have valid travel documents including a passport (valid for at least 6 months beyond your travel date), necessary visas, and any required vaccination certificates (including Yellow Fever where applicable). 7.2 Our visa assistance service is provided on a consultancy basis. We prepare and submit applications on your behalf, but final approval rests entirely with the relevant government authorities. We do not guarantee visa approval. 7.3 You are responsible for ensuring compliance with all entry requirements for your chosen destination. We are not liable for denied entry due to inadequate travel documents.' },
        { heading: '8. Travel Insurance', content: 'We strongly recommend that all travellers purchase comprehensive travel insurance before departure. Your policy should cover: (a) Medical emergencies and hospitalisation abroad; (b) Trip cancellation and curtailment; (c) Lost, stolen, or damaged luggage and personal belongings; (d) Emergency evacuation and repatriation; (e) Personal liability. Travel insurance is not included in our package prices unless explicitly stated. Zeno Africa Adventures is not responsible for any losses or expenses that would have been covered by adequate travel insurance.' },
        { heading: '9. Customer Obligations', content: 'By booking with us, you agree to: (a) Comply with all local laws, customs, and regulations at your travel destination; (b) Follow the instructions of your tour guide and respect safety protocols, especially during wildlife safaris and adventure activities; (c) Treat accommodation providers, staff, and fellow travellers with respect; (d) Inform us of any medical conditions, dietary restrictions, or accessibility needs at the time of booking; (e) Not engage in illegal, dangerous, or disruptive behaviour during your trip. We reserve the right to terminate your booking without refund if your behaviour endangers yourself or others.' },
        { heading: '10. Limitation of Liability', content: '10.1 Zeno Africa Adventures acts as an intermediary between travellers and third-party service providers including hotels, airlines, ground transport operators, and activity operators. 10.2 We are not liable for: (a) Acts, omissions, or negligence of third-party service providers; (b) Loss, theft, or damage to personal property; (c) Delays, cancellations, or changes caused by weather, natural disasters, political instability, pandemics, or force majeure events; (d) Personal injury or death except where caused by our proven negligence; (e) Any loss or damage not arising from our direct breach of contract. 10.3 Our total liability shall not exceed the total amount paid by you for the booking giving rise to the claim. 10.4 Nothing in these terms excludes or limits liability for fraud, gross negligence, or death/personal injury caused by our negligence.' },
        { heading: '11. Force Majeure', content: 'Neither party shall be liable for failure to perform obligations under these terms if performance is prevented or delayed by circumstances beyond reasonable control, including but not limited to: natural disasters, epidemics or pandemics, wars, civil unrest, government actions or travel bans, strikes, extreme weather, and infrastructure failures. In such events, we will make reasonable efforts to reschedule your trip or provide credit for future travel. If rescheduling is not possible, a refund less any irrecoverable costs incurred by third-party providers will be issued.' },
        { heading: '12. Intellectual Property', content: 'All content on this website including text, images, logos, graphics, videos, itineraries, and package descriptions are the property of Zeno Africa Adventures or our licensors and are protected by copyright and trademark laws. You may not reproduce, distribute, modify, or create derivative works from any content without our prior written consent. User-generated content such as reviews and feedback may be used by us for marketing purposes.' },
        { heading: '13. Reviews and Testimonials', content: 'By leaving a review or testimonial on our platform or social media, you grant Zeno Africa Adventures a non-exclusive, royalty-free, perpetual licence to use, reproduce, and display your review in our marketing materials. Reviews must be honest and based on genuine experiences. We reserve the right to remove reviews that contain false information, offensive language, or spam.' },
        { heading: '14. Governing Law and Disputes', content: 'These Terms of Service are governed by and construed in accordance with the laws of the United Republic of Tanzania. Any disputes arising from these terms or your use of our services shall be resolved through: (a) Informal negotiation — contact us at zenoafricaadventures@gmail.com to attempt resolution; (b) Mediation — if informal resolution fails, both parties agree to submit to mediation before initiating legal proceedings; (c) Arbitration — unresolved disputes shall be settled by binding arbitration under the Arbitration Act of Tanzania, with the seat of arbitration in Dar es Salaam. The language of arbitration shall be English.' },
        { heading: '15. Amendments', content: 'We reserve the right to modify these Terms of Service at any time. Changes will be effective immediately upon posting on this page with an updated "Last Updated" date. Material changes will be communicated via email to registered users. Your continued use of our services after changes are posted constitutes acceptance of the modified terms.' },
        { heading: '16. Severability', content: 'If any provision of these terms is found to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the remaining provisions shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable while preserving its original intent.' },
        { heading: '17. Contact Information', content: 'For any questions about these Terms of Service, please contact: Zeno Africa Adventures — Email: zenoafricaadventures@gmail.com — Phone: +255 674 448 795 — Website: zenoafricaadventures.com — Address: Tanzania, East Africa.' },
      ]}
    />
  );
}

export function RefundPolicyPage() {
  return (
    <LegalPage
      title="Refund Policy"
      description="Zeno Africa Adventures Refund Policy — eligibility criteria, refund process, timelines, and non-refundable items for safari bookings, hotel reservations, and travel services."
      path="/refund"
      lastUpdated="July 2025"
      sections={[
        { heading: '1. Overview', content: 'At Zeno Africa Adventures, we understand that plans can change. This Refund Policy outlines the terms and conditions under which refunds are issued for bookings, visa services, and other payments made through our platform. All refunds are processed in accordance with this policy and our Terms of Service.' },
        { heading: '2. Deposit Refunds', content: 'Your initial deposit is partially refundable based on the cancellation timeline: (a) More than 60 days before travel: 90% of your deposit is refundable; (b) 31-60 days before travel: 50% of your deposit is refundable; (c) 15-30 days before travel: 25% of your deposit is refundable; (d) Less than 14 days before travel: Your deposit is non-refundable. Note: Deposits for gorilla trekking permits, chimpanzee permits, and other third-party reservations may be entirely non-refundable due to supplier policies. These restrictions will be clearly communicated at the time of booking.' },
        { heading: '3. Full Payment Refunds', content: 'If you have paid in full and cancel your booking, the refund amount is calculated on the total amount paid, following the same tiered timeline: (a) More than 60 days before travel: 90% refund; (b) 31-60 days before travel: 50% refund; (c) 15-30 days before travel: 25% refund; (d) Less than 14 days before travel: No refund.' },
        { heading: '4. How to Request a Refund', content: 'To request a refund: (a) Log into your account on our website; (b) Navigate to "My Bookings" in your dashboard; (c) Select the booking you wish to cancel and click "Cancel Booking"; (d) Alternatively, email us at zenoafricaadventures@gmail.com with your full name, booking reference number, and reason for cancellation. All cancellation requests are acknowledged within 24 hours. Please do not assume a refund has been processed until you receive written confirmation from our team.' },
        { heading: '5. Refund Processing Time', content: 'Once your refund is approved: (a) Credit/debit card refunds are processed within 5-10 business days and will appear on your statement within 1-2 billing cycles; (b) Bank transfer refunds may take 10-15 business days depending on your financial institution and country; (c) PayPal or mobile money refunds are processed within 3-5 business days. You will receive email notification when your refund has been processed.' },
        { heading: '6. Non-Refundable Items', content: 'The following are non-refundable under any circumstances: (a) Gorilla and chimpanzee trekking permits; (b) Government visa application fees already submitted to embassies; (c) Visa consultancy service fees once the application process has begun; (d) Third-party services already booked and confirmed on your behalf where the supplier\'s policy prohibits refunds; (e) Peak-season or promotional bookings explicitly marked as non-refundable at the time of purchase.' },
        { heading: '7. Company-Initiated Refunds', content: 'If we cancel or significantly modify your booking due to circumstances within our control, you are entitled to: (a) A full refund of all amounts paid, including non-refundable items listed above; (b) Alternatively, rebooking on an alternative date or package of comparable or higher value at no additional cost; (c) Compensation for reasonable out-of-pocket expenses incurred as a direct result of the cancellation, up to the value of your booking.' },
        { heading: '8. Force Majeure Refunds', content: 'In the event of cancellations due to circumstances beyond our control (natural disasters, pandemics, government travel bans, civil unrest), we offer: (a) Full rescheduling to an alternative date within 18 months at no additional cost; (b) Credit voucher valid for 24 months for use on any Zeno Africa Adventures package; (c) If rescheduling or credit is not possible, a refund of all amounts paid minus any irrecoverable costs incurred by third-party providers on your behalf. Irrecoverable costs will be documented and communicated transparently.' },
        { heading: '9. Chargebacks and Disputes', content: 'We encourage you to contact us directly to resolve any payment disputes before initiating a chargeback with your bank or credit card company. Chargebacks filed without prior contact may result in additional fees and account suspension. We will provide documentation to support the legitimacy of charges when required by payment processors.' },
        { heading: '10. Group Booking Refunds', content: 'For group bookings of 8 or more travellers: (a) Individual cancellations within a group follow the standard refund timeline; (b) If the entire group cancels, the refund follows the standard timeline; (c) If the group size reduces below the minimum required for special group rates, the remaining members may be subject to rate adjustment; (d) A group booking coordinator must submit all cancellation requests on behalf of the group.' },
        { heading: '11. Contact Us', content: 'For refund questions or assistance, please contact: Zeno Africa Adventures — Email: zenoafricaadventures@gmail.com — Phone: +255 674 448 795 — Our team is available Monday to Friday, 8:00 AM to 6:00 PM EAT.' },
      ]}
    />
  );
}

export default { PrivacyPolicyPage, TermsPage, RefundPolicyPage };
